### ISSUE TITLE
Neovim

### ISSUE THREAD

**Issue by nickmagginas** [potassco/tree-sitter-clingo#9]
Hi are any of you by any chance using this with neovim. I have had no look integrating with the editor.

**Comment by sthiele** [comment]
Neovim has experimental support for tree-sitter parsers via the plugin https://github.com/nvim-treesitter/nvim-treesitter
I'm myself not a neovim user but one could try to add tree-sitter-clingo as supported language parser.

**Comment by nickmagginas** [comment]
Hi. Yes I am aware and the way to install third party parsers is documented but it appears this specific parser needs to be installed in some non standard way. Was just wondering if maybe any of you were using neovim as your editor and had figured out how to use the parser with the plugin. As it seems this is not the case I am closing this. Thank you very much for your quick reply.

**Comment by nickmagginas** [comment]
If anyone stumbles upon this in the future:

Neovim obviously does not have a filetype plugin for .lp programs. You can add it with 

```lua
vim.filetype.add({ extension = { lp = "lp" }})
```

obviously some equivalent way will work in Vimscript. Then you can add the parser with 

```lua
local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
    parser_configs.clingo = {
      install_info = {
	url = "https://github.com/potassco/tree-sitter-clingo",
	files = { "src/parser.c" },
	branch = "main"
      },
      filetype = "lp"
    }
```

You can then install the parser ```:TSInstall clingo```

This will make the parser work if you want highlights you need to define a highlights file ```~/.config/nvim/queries/clingo/highlights.scm``` that might look like this

```
(NUMBER) @number
(VARIABLE) @type
(IF) @operator
(DOTS) @punctuation.delimeter
(DOT) @punctuation.delimeter
(LPAREN) @function.call
(RPAREN) @function.call
(SEM) @punctuation.delimeter
(identifier) @constructor
(SHOW) @function
(term (identifier)) @string
(LBRACE) @function.call
(RBRACE) @function.call
(SLASH) @punctuation.delimeter
(NOT) @operator
(single_comment) @comment
(multi_comment) @comment
```
